### ISSUE TITLE
AssertionError: timing must be a ValueNumber

### ISSUE THREAD

**Issue by theompm** [CODEX-CELIDA/execution-engine#115]
Hi Gregor,

ich habe leider einen neuen Fehler.

```
covid19-inpatient-therapy/recommendation/covid19-abdominal-positioning-ards
Traceback (most recent call last):
  File "/home/theo/projects/execution-engine/scripts/execute.py", line 92, in <module>
    cdd = e.load_recommendation(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/execution_engine.py", line 275, in load_recommendation
    recommendation = self.load_recommendation_from_database(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/execution_engine.py", line 408, in load_recommendation_from_database
    recommendation = cohort.Recommendation.from_json(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/serializable.py", line 64, in from_json
    return cls.from_dict(json.loads(data))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/cohort/recommendation.py", line 273, in from_dict
    pi_pairs=[
             ^
  File "/home/theo/projects/execution-engine/execution_engine/omop/cohort/recommendation.py", line 274, in <listcomp>
    cohort.PopulationInterventionPair.from_dict(c)
  File "/home/theo/projects/execution-engine/execution_engine/omop/cohort/population_intervention_pair.py", line 252, in from_dict
    intervention=CriterionCombination.from_dict(data["intervention"]),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/criterion/combination.py", line 194, in from_dict
    combination.add(criterion_factory(**criterion))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/criterion/factory.py", line 64, in criterion_factory
    return class_map[class_name].from_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/criterion/combination.py", line 194, in from_dict
    combination.add(criterion_factory(**criterion))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/criterion/factory.py", line 64, in criterion_factory
    return class_map[class_name].from_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/projects/execution-engine/execution_engine/omop/criterion/procedure_occurrence.py", line 186, in from_dict
    isinstance(timing, ValueNumber) or timing is None
                                       ^^^^^^^^^^^^^^
AssertionError: timing must be a ValueNumber
```

## unsere dtypes  in procedure_occurrence:

```
"column_name"	"data_type"
"procedure_occurrence_id"	"integer"
"person_id"	"integer"
"procedure_concept_id"	"integer"
"procedure_date"	"date"
"procedure_datetime"	"timestamp with time zone"
"procedure_end_date"	"date"
"procedure_end_datetime"	"timestamp with time zone"
"procedure_type_concept_id"	"integer"
"modifier_concept_id"	"integer"
"quantity"	"integer"
"provider_id"	"integer"
"visit_occurrence_id"	"integer"
"visit_detail_id"	"integer"
"procedure_source_value"	"character varying"
"procedure_source_concept_id"	"integer"
"modifier_source_value"	"character varying"
```

**Comment by glichtner** [comment]
Hi @theompm,

das ist ein Problem mit dem Datentyp in der FHIR Repräsentation, nicht in eurer Datenbank. Hast du den recommendation server mal neugestartet (und vorher sicherheitshalber nochmal gepullt)?
```
docker stop celida-recommendation-server
docker rm celida-recommendation-server
docker pull glichtner/celida-recommendation-server:latest
docker restart celida-recommendation-server
```

**Comment by theompm** [comment]
Hi @glichtner 

# SOLUTION

uncommennt  -> reload recommendations


```python

# Optional: Truncate all tables before execution
with omopdb.begin() as con:
    con.execute(
        text(
            "TRUNCATE TABLE "
            "   celida.comment, "
            "   celida.recommendation, "
            "   celida.criterion, "
            "   celida.execution_run, "
            "   celida.result_interval, "
            "   celida.recommendation, "
            "   celida.population_intervention_pair "
            "RESTART IDENTITY"
        )
    )

```
